---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-iter8
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: app-name
      description: application name
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: registry-namespace
      description: container registry namespace
    - name: image-name
      description: image name
    - name: path-to-dockerfile
      default: "."
    - name: pipeline-debug
      default: "0"
    - name: cluster-name
      description: the name of the cluster to target
    - name: apikey
    - name: dev-region
    - name: dev-resource-group
    - name: dev-cluster-namespace
      description: namespace dev
    - name: grafana-dashboard-url
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: iter8-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: iter8-$(uid)
      spec:
        pipelineRef:
          name: iter8-pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: app-name
            value: $(params.app-name)
          - name: registry-region
            value: $(params.registry-region)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: image-name
            value: $(params.image-name)
          - name: path-to-dockerfile
            value: $(params.path-to-dockerfile)
          - name: dev-region
            value: $(params.dev-region)
          - name: dev-resource-group
            value: $(params.dev-resource-group)
          - name: apikey
            value: $(params.apikey)
          - name: cluster-name
            value: $(params.cluster-name)
          - name: dev-cluster-namespace
            value: $(params.dev-cluster-namespace)
          - name: grafana-dashboard-url
            value: $(params.grafana-dashboard-url)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: iter8-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-manual
spec:
  params:
    - name: repository
      value: "$params.repository"
    - name: branch
      value: "$params.branch"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - binding:
        name: trigger-binding-manual
      template:
        name: trigger-template-iter8
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: branch
      value: "$(event.ref)"
    - name: revision
      value: "$(event.head_commit.id)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-commit
spec:
  triggers:
    - binding:
        name: github-commit
      template:
        name: trigger-template-iter8
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: grit-or-gitlab-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.git_http_url)"
    - name: branch
      value: "$(event.ref)"
    - name: revision
      value: "$(event.checkout_sha)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: grit-or-gitlab-commit
spec:
  triggers:
    - binding:
        name: grit-or-gitlab-commit
      template:
        name: trigger-template-iter8
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bitbucket-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.links.html.href)"
    - name: revision
      value: "$(event.push.changes[0].new.target.hash)"
    - name: branch
      value: "$(event.push.changes[0].new.name)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-commit
spec:
  triggers:
    - binding:
        name: bitbucket-commit
      template:
        name: trigger-template-iter8
