---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .pipeline
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: container-registry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: toolchain
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: devops-insights
  - type: git
    branch: trialv1
    service: ${TEKTON_CATALOG_REPO}
    path: temp/docker
  - type: git
    branch: trialv1
    service: ${TEKTON_CATALOG_REPO}
    path: temp/iks
  - type: git
    branch: trialv1
    service: ${TEKTON_CATALOG_REPO}
    path: temp/utils
triggers:
  - type: manual
    name: manual-trigger
    eventListener: manual-run
    properties:
      - type: text
        name: branch
        value: master
      - type: text
        name: repository
        value: ${APP_REPO_FULL}
  - type: manual
    name: immediate-rollforward
    eventListener: manual-rollforward
    properties:
      - type: text
        name: experiment-name
        value: ""
  - type: manual
    name: immediate-rollback
    eventListener: manual-rollback
    properties:
      - type: text
        name: experiment-name
        value: ""
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${APP_REPO}
    branch: master
    events: { "push": true }
properties:
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - name: apikey
    value: ${API_KEY}
    type: SECURE
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: image-name
    value: ${APP_NAME}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: dev-cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${PROD_REGION_ID}
    type: text
  - name: cluster-name
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${PROD_RESOURCE_GROUP}
    type: text
  - name: grafana-dashboard-url
    value: ${ROLLOUT_DASHBOARD}
    type: text
