---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .south-pipeline
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: container-registry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: toolchain
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: devops-insights
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: kubernetes-service
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: linter
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: utils
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: cra
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: tester
triggers:
  - type: manual
    name: immediate-rollforward
    eventListener: manual-rollforward
    properties:
      - type: text
        name: experiment-name
        value: ""
      - name: branch
        type: text
        value: ${APP_REPO_BRANCH}
  - type: manual
    name: immediate-rollback
    eventListener: manual-rollback
    properties:
      - type: text
        name: experiment-name
        value: ""
      - name: branch
        type: text
        value: ${APP_REPO_BRANCH}
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${APP_REPO}
    branch: ${APP_REPO_BRANCH}
    events: { "push": true }
  - type: manual
    name: manual-run
    eventListener: manual-run
    properties:
      - name: branch
        type: text
        value: ${APP_REPO_BRANCH}

properties:
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - name: apikey
    value: ${API_KEY}
    type: SECURE
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: image-name
    value: ${APP_NAME}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: dev-cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${PROD_REGION_ID}
    type: text
  - name: cluster-name
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${PROD_RESOURCE_GROUP}
    type: text
  - name: grafana-dashboard-url
    value: ${ROLLOUT_DASHBOARD}
    type: text
  - name: commons-hosted-region
    value: ${COMMONS_HOSTED_REGION}
    type: text
